version: '3'

services:
  cosmos-testnet:
    container_name: cosmos-testnet
    image: docker-cosmos:testnet-latest
    environment: 
      - MONIKER=NodeName
      - CHAIN_ID=stargate-final
      - GENESIS_URL=https://raw.githubusercontent.com/cosmos/stargate-launch/master/genesis.json
      - GAIAD_HOME=/.gaiad
    restart: always
    ports:
      - "26656:26656"
      - "26657:26657"
      - "26658:26658"
      - "26660:26660"
      - "1317:1317" # for rest-server
    volumes:
      - cosmos-testnet-data:/.gaiad
  prometheus:
    container_name: prometheus
    image: ryanhendricks/docker-prometheus:latest
    environment: 
      - PROMETHEUS_L_ADDR=0.0.0.0
      - PROMETHEUS_PORT=9090
      - JOBNAME="cosmos-testnet"
      - TARGET_HOST=cosmos-testnet
      - TARGET_PORT=26660
      - INSTANCE="cosmos-testnet"
    restart: always
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
volumes:
  cosmos-testnet-data:
